---
title: "1a_Map_Study_Area"
---

This markdown contains the code for mapping the study area figure presented in the dissertation.

## Load Packages

```{r}
library(sf)
library(ggplot2)
library(cowplot)
```

## Data Loading

```{r}
# london boundaries 
london_boundary <- st_read("data/gla/London_GLA_Boundary.shp")

# london LSOA boundaries
london_lsoa <- st_read("data/lsoa_london/lsoa_london.shp")

# UK boundaries
uk_boundary <- st_read("data/raw_data/gadm41_GBR_0.json")%>%
  st_transform(.,27700)

# greenspaces > 2ha
greenspace2ha <- st_read("data/greenspace_london_2ha/greenspace_london_2ha.shp")
```

## Map Plotting

```{r}
# map london within the whole of UK
uk_london_map <- ggplot() +
  geom_sf(
    # uk boundary
    data = uk_boundary,
    fill = "white",
    colour = "grey30",
    linewidth = 0.5
  ) +
  geom_sf(
    # london boundary and fill colour
    data = london_boundary,
    fill = "#C96F57",
    colour = "grey30",
    linewidth = 0.5
  ) +
  theme_void()

uk_london_map
```

```{r}
# study area london and UGS distribution map
london_lsoa_study_area_map <- ggplot() +
  geom_sf(
    # london lsoa
    data = london_lsoa,
    fill = NA,
    colour = "grey90",
    linewidth = 0.1
  ) +
  geom_sf(
    # london boundary
    data = london_boundary,
    fill = NA,
    colour = "grey30",
    linewidth = 0.5
  ) +
  geom_sf(
    # greenspaces > 2ha 
    data = greenspace2ha,
    fill = "#A8C3A0",   # muted green
    colour = NA
  ) +
    coord_sf(
    datum = NA,
    expand = FALSE
  ) +
  theme_void()

london_lsoa_study_area_map
```

```{r}
# combine plots
combine_study_area_map <- plot_grid(
  uk_london_map,
  NULL,
  london_lsoa_study_area_map,
  labels = c("a", "b"),
  label_size = 14,
  label_fontface = "bold",
  label_x = 0.02,       
  label_y = 0.98,
  hjust = 0,
  vjust = 1,
  nrow = 1,
  align = "h",
  axis = "tb",
  rel_widths = c(1, 0.1, 3)
)

combine_study_area_map
```

```{r}
# save as png
ggsave(
  filename = "figures/Fig1_Study_Area.png",
  plot = combine_study_area_map,
  width = 11.69,
  height = 8.27,
  units = "in",
  dpi = 300,
  bg = "white"
)
```
