---
title: "Mapping_Travel_Time"
---

```{r}
# remove objects from R environment and clear memory
rm(list = ls())    
gc()
```

## Load Packages

```{r, message=FALSE, warning=FALSE}
library(sf)
library(dplyr)
library(ggplot2)
library(grid)
library(cowplot)
```

## Data Loading

```{r}
# load multimodal travel time GeoPackage 
multimodal_accessibility_lsoa <- st_read("data/multimodal_accessibility_lsoa.gpkg")
```

```{r}
# check column names
names(multimodal_accessibility_lsoa)
```

```{r}
# take minimum time
pt_dist <- multimodal_accessibility_lsoa %>%
  st_drop_geometry() %>%
  mutate(
    travel_time_min_PT = as.numeric(travel_time_min_PT)
  )

# summarise stats for min travel time
pt_dist %>%
  summarise(
    n_lsoa = n(),
    missing = sum(is.na(travel_time_min_PT)),
    min = min(travel_time_min_PT, na.rm = TRUE),
    p05 = quantile(travel_time_min_PT, 0.05, na.rm = TRUE),
    p25 = quantile(travel_time_min_PT, 0.25, na.rm = TRUE),
    median = median(travel_time_min_PT, na.rm = TRUE),
    mean = mean(travel_time_min_PT, na.rm = TRUE),
    p75 = quantile(travel_time_min_PT, 0.75, na.rm = TRUE),
    p90 = quantile(travel_time_min_PT, 0.90, na.rm = TRUE),
    p95 = quantile(travel_time_min_PT, 0.95, na.rm = TRUE),
    max = max(travel_time_min_PT, na.rm = TRUE)
  )
```

## Mapping Reference

<https://ipeagit.github.io/intro_access_book/9_aopdata_acessibilidade.en.html>

## 1. Travel time to the nearest oppportunity (CE UGS)

```{r}
# Convert the three travel-time columns from wide to long format
travel_time_long <- multimodal_accessibility_lsoa %>%
  dplyr::select(
    LSOA21CD,
    travel_time_min_PT,
    travel_time_min_walk,
    travel_time_min_cycle
  ) %>%
  tidyr::pivot_longer(
    cols = starts_with("travel_time_min_"),
    names_to = "mode",
    values_to = "travel_time_min"
  ) %>%
  # rename for visualisation of each map's title
  dplyr::mutate(
    mode = dplyr::recode(
      mode,
      "travel_time_min_PT"    = "Public Transit",
      "travel_time_min_walk"  = "Walking",
      "travel_time_min_cycle" = "Cycling"
    ),
    
    # Control the order of the facet panels
    mode = factor(
      mode,
      levels = c("Public Transit", "Walking", "Cycling")
    )
  )
```

```{r}
# plot
min_travel_time <- ggplot(travel_time_long) +
  # minimum travel time
  geom_sf(
    aes(fill = travel_time_min),
    colour = NA
  ) +
  # use continuous colour scale from 0 to 50 minutes
  scale_fill_viridis_c(
    option = "rocket",
    direction = -1,
    limits = c(0, 50),
    breaks = seq(0, 50, 10),
    labels = seq(0, 50, 10),
    oob = scales::squish,
    # missing values as light grey
    na.value = "grey90"
  ) +
  # plot in one row  
  facet_wrap(
    ~ mode,
    nrow = 1
  ) +
  # map legend title
  labs(
    fill = "Minimum travel\ntime (minutes)"
  ) +
  coord_sf(
    datum = NA,
    expand = FALSE
  ) +
  guides(
    fill = guide_colourbar(
      title.position = "top",
      title.hjust = 0.5,
      barheight = unit(5, "cm"),
      barwidth = unit(0.7, "cm")
    )
  ) +
  theme_void() +
  theme(
    # add space between titles and maps
    strip.text.x = element_text(
      size = 15,
      margin = margin(
        t = 5,
        b = 18
      )
    ),

    # add space between the three maps
    panel.spacing.x = unit(1.2, "cm"),

    legend.position = "right",
    
    legend.title = element_text(
      size = 12,
      lineheight = 0.9
    ),

    legend.text = element_text(
      size = 10
    ),

    # add space around the whole figure
    plot.margin = margin(
      t = 15,
      r = 20,
      b = 15,
      l = 20
    )
  )

min_travel_time
```

```{r}
# save as PNG
ggsave(
  filename = "figures/Fig11_Minimum_Travel_Time.png",
  plot = min_travel_time,
  width = 11.69, 
  height = 5.5,
  units = "in",
  dpi = 300,
  bg = "white"
)
```

## 2. Cummulative Accessibility

```{r}
# name the six accessibility variables
access_columns <- c(
  "access_score_15_PT",
  "access_score_60_PT",
  "access_score_15_walk",
  "access_score_60_walk",
  "access_score_15_cycle",
  "access_score_60_cycle"
)
```

```{r}
# calculate LSOAs with no reachable CE UGS

# drop geometry 
access_values <- multimodal_accessibility_lsoa %>%
  st_drop_geometry() %>%
  dplyr::select(all_of(access_columns))

zero_access_summary <- access_values %>%
  tidyr::pivot_longer(
    cols = everything(),
    names_to = "access_measure",
    values_to = "access_score"
  ) %>%
  dplyr::group_by(access_measure) %>%
  dplyr::summarise(
    n_lsoa = sum(!is.na(access_score)),
    n_zero = sum(access_score == 0, na.rm = TRUE),
    percent_zero = (n_zero / n_lsoa) * 100,
    .groups = "drop"
  ) %>%
  dplyr::mutate(
    percent_zero = round(percent_zero, 2)
  )

zero_access_summary
```

```{r}
# plotting function
access_map <- function(data, variable, mode_title, threshold_title) {
  ggplot(data) +
    geom_sf(
      aes(fill = .data[[variable]]),
      colour = NA,
      linewidth = 0
    ) +
    scale_fill_viridis_c(
      option = "rocket",
      # limit to 100 opportunities 
      limits = c(0, 100),
      # set colour breaks 
      breaks = c(0, 25, 50, 75, 100),
      labels = c("0", "25", "50", "75", "100+"),
      oob = scales::squish,
      na.value = "grey90",
      name = "CE UGS\nOpportunities\n"
    ) +
    labs(
      title = mode_title,
      subtitle = threshold_title
    ) +
    coord_sf(
      datum = NA,
      expand = FALSE
    ) +
    theme_void() +
    theme(
      plot.title = element_text(
        size = 10,
        hjust = 0.5,
        margin = margin(b = 2)
      ),
      plot.subtitle = element_text(
        size = 10,
        hjust = 0.5,
        margin = margin(b = 8)
      ),
      plot.margin = margin(5, 5, 5, 5),
      legend.title = element_text(
        size = 10,
        lineheight = 0.9
      ),
      legend.text = element_text(size = 9)
    )
}
```

```{r}
# for each mode and time threshold: 

# public transit 15 min
PT_15 <- access_map(
  multimodal_accessibility_lsoa,
  "access_score_15_PT",
  "Public Transit",
  "Up to 15 minutes"
)

# public transit 60 min
PT_60 <- access_map(
  multimodal_accessibility_lsoa,
  "access_score_60_PT",
  "Public Transit",
  "Up to 60 minutes"
)

# walking 15 min
walk_15 <- access_map(
  multimodal_accessibility_lsoa,
  "access_score_15_walk",
  "Walking",
  "Up to 15 minutes"
)

# walking 60 min
walk_60 <- access_map(
  multimodal_accessibility_lsoa,
  "access_score_60_walk",
  "Walking",
  "Up to 60 minutes"
)

# cycling 15 min
cycle_15 <- access_map(
  multimodal_accessibility_lsoa,
  "access_score_15_cycle",
  "Cycling",
  "Up to 15 minutes"
)

# cycling 60 min
cycle_60 <- access_map(
  multimodal_accessibility_lsoa,
  "access_score_60_cycle",
  "Cycling",
  "Up to 60 minutes"
)
```

```{r}
# make shared legend
shared_legend <- cowplot::get_legend(
  PT_60 +
    theme(
      legend.position = "right",
      legend.box.margin = margin(0, 0, 0, 8)
    )
)
```

```{r}
# set legend for each plot as no legend --> to use a shared legend later
PT_15_no_legend <- PT_15 + theme(legend.position = "none")
PT_60_no_legend <- PT_60 + theme(legend.position = "none")
walk_15_no_legend <- walk_15 + theme(legend.position = "none")
walk_60_no_legend <- walk_60 + theme(legend.position = "none")
cycle_15_no_legend <- cycle_15 + theme(legend.position = "none")
cycle_60_no_legend <- cycle_60 + theme(legend.position = "none")
```

```{r}
# cowplot combine maps 3 rows 2 columns plot
map_grid <- cowplot::plot_grid(
  PT_15_no_legend,
  PT_60_no_legend,
  walk_15_no_legend,
  walk_60_no_legend,
  cycle_15_no_legend,
  cycle_60_no_legend,
  ncol = 2,
  align = "hv",
  axis = "tblr",
  rel_heights = c(1, 1, 1)
)

# legend
maps_with_legend <- cowplot::plot_grid(
  map_grid,
  shared_legend,
  ncol = 2,
  rel_widths = c(1, 0.16)
)


access_score_maps <- cowplot::ggdraw() +
  cowplot::draw_plot(
    maps_with_legend,
    x = 0,
    y = 0,
    width = 1,
    height = 0.94
  )

access_score_maps
```

```{r}
# save as PNG
ggsave(
  filename = "figures/Fig12_Cumulative_Opportunity_Accessibility.png",
  plot = access_score_maps,
  width = 8,
  height = 9,
  units = "in",
  dpi = 300,
  bg = "white"
)
```
