---
title: "Mapping_Travel_Time"
---

```{r}
# remove objects from R environment and clear memory
rm(list = ls())    
gc()
```

## Load Packages

```{r, message=FALSE, warning=FALSE}
library(sf)
library(here)
library(dplyr)
library(stringr)
library(tmap)
library(ggplot2)
library(cowplot)
library(viridis)
library(purrr)
library(tidyverse)
library(tidytransit)
```

## Data Loading

**Multimodal Travel Time (exported from 6_Multimodal_Travel_Time_r5r)**

```{r}
# load the saved GeoPackage
multimodal_travel_time_lsoa <- st_read("data/multimodal_travel_time_lsoa/multimodal_travel_time_lsoa.gpkg")
```

```{r}
names(multimodal_travel_time_lsoa)
```

```{r}
pt_dist <- multimodal_travel_time_lsoa %>%
  st_drop_geometry() %>%
  mutate(
    travel_time_min_PT = as.numeric(travel_time_min_PT)
  )

pt_dist %>%
  summarise(
    n_lsoa = n(),
    missing = sum(is.na(travel_time_min_PT)),
    min = min(travel_time_min_PT, na.rm = TRUE),
    p05 = quantile(travel_time_min_PT, 0.05, na.rm = TRUE),
    p25 = quantile(travel_time_min_PT, 0.25, na.rm = TRUE),
    median = median(travel_time_min_PT, na.rm = TRUE),
    mean = mean(travel_time_min_PT, na.rm = TRUE),
    p75 = quantile(travel_time_min_PT, 0.75, na.rm = TRUE),
    p90 = quantile(travel_time_min_PT, 0.90, na.rm = TRUE),
    p95 = quantile(travel_time_min_PT, 0.95, na.rm = TRUE),
    max = max(travel_time_min_PT, na.rm = TRUE)
  )
```

## Map LSOAs Travel Time by Borough

**1. Borough Names**

```{r}
# extract borough name from LSOA21NM
multimodal_travel_time_lsoa2 <- multimodal_travel_time_lsoa %>%
  mutate(
    borough_name = str_remove(LSOA21NM, "\\s+\\d{3}[A-Z]$")
  )

# check boroughs
sort(unique(multimodal_travel_time_lsoa2$borough_name))
```

```{r}
# make map function for each borough
make_borough_map <- function(data, borough, travel_var) {
  
  travel_limits <- range(data[[travel_var]], na.rm = TRUE)
  
  data_borough <- data %>%
    filter(borough_name == borough)
  
  ggplot(data_borough) +
    geom_sf(
      aes(fill = .data[[travel_var]]),
      colour = "white",
      linewidth = 0.08
    ) +
    scale_fill_viridis_c(
      option = "plasma",
      direction = -1,
      limits = travel_limits,
      name = "Travel time\n(min)"
    ) +
    coord_sf(datum = NA) +
    labs(title = borough) +
    theme_void() +
    theme(
      plot.title = element_text(
        face = "bold",
        size = 9,        # smaller borough name
        hjust = 0.5,     # centre title
        margin = margin(b = 2)
      ),
      plot.title.position = "plot",
      legend.position = "bottom"
    )
}
```

```{r}
travel_var <- "travel_time_min_PT"
# travel_var <- "travel_time_min_walking"
# travel_var <- "travel_time_min_cycling"
```

```{r}
borough_names <- sort(unique(multimodal_travel_time_lsoa2$borough_name))

borough_maps_PT <- map(
  borough_names,
  ~ make_borough_map(
    data = multimodal_travel_time_lsoa2,
    borough = .x,
    travel_var = travel_var
  )
)

names(borough_maps_PT) <- borough_names
```

```{r}
# extract one shared legend
shared_legend <- get_legend(
  borough_maps_PT[["Camden"]] +
    theme(
      legend.position = "bottom",
      legend.box.margin = margin(t = 5)
    )
)
```

```{r}
# remove legends from all maps
borough_maps_PT_nolegend <- map(
  borough_maps_PT,
  ~ .x + theme(legend.position = "none")
)
```

```{r}
borough_map1 <- plot_grid(
  borough_maps_PT_nolegend[["Barking and Dagenham"]],
  borough_maps_PT_nolegend[["Barnet"]],
  borough_maps_PT_nolegend[["Bexley"]],
  borough_maps_PT_nolegend[["Brent"]],
  borough_maps_PT_nolegend[["Bromley"]],
  borough_maps_PT_nolegend[["Camden"]],
  borough_maps_PT_nolegend[["City of London"]],
  borough_maps_PT_nolegend[["Croydon"]],
  borough_maps_PT_nolegend[["Ealing"]],
  borough_maps_PT_nolegend[["Enfield"]],
  borough_maps_PT_nolegend[["Greenwich"]],
  borough_maps_PT_nolegend[["Hackney"]],
  ncol = 3
)

# add shared legend underneath
plot_borough_map1 <- plot_grid(
  borough_map1,
  shared_legend,
  ncol = 1,
  rel_heights = c(1, 0.08)
)

plot_borough_map1
```

```{r}
ggsave(
  "figures/borough_travel_time_PT1.png",
  plot_borough_map1,
  width = 8.27,
  height = 11.69,
  units = "in",
  dpi = 300,
  bg = "white"
)
```

```{r}
borough_map_2 <- plot_grid(
  borough_maps_PT_nolegend[["Hammersmith and Fulham"]],
  borough_maps_PT_nolegend[["Haringey"]],
  borough_maps_PT_nolegend[["Harrow"]],
  borough_maps_PT_nolegend[["Havering"]],
  borough_maps_PT_nolegend[["Hillingdon"]],
  borough_maps_PT_nolegend[["Hounslow"]],
  borough_maps_PT_nolegend[["Islington"]],
  borough_maps_PT_nolegend[["Kensington and Chelsea"]],
  borough_maps_PT_nolegend[["Kingston upon Thames"]],
  borough_maps_PT_nolegend[["Lambeth"]],
  borough_maps_PT_nolegend[["Lewisham"]],
  borough_maps_PT_nolegend[["Merton"]],
  ncol = 3
)

# add shared legend underneath
plot_borough_map2 <- plot_grid(
  borough_map_2,
  shared_legend,
  ncol = 1,
  rel_heights = c(1, 0.08)
)

plot_borough_map2
```

```{r}
ggsave(
  "figures/borough_travel_time_PT2.png",
  plot_borough_map2,
  width = 8.27,
  height = 11.69,
  units = "in",
  dpi = 300,
  bg = "white"
)
```

```{r}
borough_map_3 <- plot_grid(
  borough_maps_PT_nolegend[["Newham"]],
  borough_maps_PT_nolegend[["Redbridge"]],
  borough_maps_PT_nolegend[["Richmond upon Thames"]],
  borough_maps_PT_nolegend[["Southwark"]],
  borough_maps_PT_nolegend[["Sutton"]],
  borough_maps_PT_nolegend[["Tower Hamlets"]],
  borough_maps_PT_nolegend[["Wandsworth"]],
  borough_maps_PT_nolegend[["Westminster"]],
  ncol = 3
)

# add shared legend underneath
plot_borough_map3 <- plot_grid(
  borough_map_3,
  shared_legend,
  ncol = 1,
  rel_heights = c(1, 0.08)
)

plot_borough_map3
```

```{r}
ggsave(
  "figures/borough_travel_time_PT3.png",
  plot_borough_map3,
  width = 8.27,
  height = 11.69,
  units = "in",
  dpi = 300,
  bg = "white"
)
```
